### ISSUE TITLE
"Tasks" vs "Chores"

### ISSUE THREAD

**Issue by Imaginativeone** [YoshiTunaiga/Algo-Explained#1]
What's the distinction between a "task" and a "chore"?

**Comment by YoshiTunaiga** [comment]
My apologies for the late response @Imaginativeone. I missed this Issue notification in my email.

By now you might have answered your questions. However, here is what I know:
- Task: adds new functionality
- Chore: means maintenance work that might not add functionality

After some research for rule of thumbs and patterns, I came across the Semantic Commit Messages:
https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

Hope this helps.
